//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int Bank_Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
